version: "2"
run:
  timeout: 5m
  allow-parallel-runners: true
linters:
  default: standard
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - decorder
    - gocritic
    - gocyclo
    - gosec
    - zerologlint
    - testifylint
    - paralleltest
    - copyloopvar
    - godox
    - revive
  settings:
    godox:
      keywords:
        - "DEBUG"
        - "TODO"

formatters:
  enable:
    - gofmt
    - goimports
    - golines
  settings:
    goimports:
      local-prefixes:
        - github.com/smartcontractkit/quarantine
    golines:
      max-len: 120
