name: Lint and Test (junit-enhancer)
on:
  push:
      branches:
        - main
      tags:
        - '*'
  pull_request:
      branches:
        - main

jobs:
  lint:
    name: Lint 
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.7

      - name: Install Dependencies
        working-directory: cmd/junit-enhancer
        run: go mod download

      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          working-directory: cmd/junit-enhancer
          version: latest

  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.7

      - name: Install Dependencies
        working-directory: cmd/junit-enhancer
        run: |
          echo "::group::Installing dependencies"
          go mod download
          echo "::end-group::"

          echo "::group::Installing gotestsum"
          go install gotest.tools/gotestsum@latest
          echo "::end-group::"

      - name: Test
        working-directory: cmd/junit-enhancer
        run: go test -cover ./...

  test-race:
    name: Test (race)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.7

      - name: Install Dependencies
        working-directory: cmd/junit-enhancer
        run: |
          echo "::group::Installing dependencies"
          go mod download
          echo "::end-group::"

          echo "::group::Installing gotestsum"
          go install gotest.tools/gotestsum@latest
          echo "::end-group::"

      - name: Test
        working-directory: cmd/junit-enhancer
        run: go test -race ./...
